// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gtstore.proto

#include "gtstore.pb.h"
#include "gtstore.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace gtstore {

static const char* ManagerService_method_names[] = {
  "/gtstore.ManagerService/Register",
  "/gtstore.ManagerService/GetNodeForKey",
};

std::unique_ptr< ManagerService::Stub> ManagerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ManagerService::Stub> stub(new ManagerService::Stub(channel));
  return stub;
}

ManagerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Register_(ManagerService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetNodeForKey_(ManagerService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ManagerService::Stub::Register(::grpc::ClientContext* context, const ::gtstore::RegisterNodeRequest& request, ::gtstore::RegisterNodeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Register_, context, request, response);
}

void ManagerService::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::gtstore::RegisterNodeRequest* request, ::gtstore::RegisterNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void ManagerService::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::RegisterNodeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void ManagerService::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::gtstore::RegisterNodeRequest* request, ::gtstore::RegisterNodeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

void ManagerService::Stub::experimental_async::Register(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::RegisterNodeResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtstore::RegisterNodeResponse>* ManagerService::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::gtstore::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::RegisterNodeResponse>::Create(channel_.get(), cq, rpcmethod_Register_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::gtstore::RegisterNodeResponse>* ManagerService::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::gtstore::RegisterNodeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::RegisterNodeResponse>::Create(channel_.get(), cq, rpcmethod_Register_, context, request, false);
}

::grpc::Status ManagerService::Stub::GetNodeForKey(::grpc::ClientContext* context, const ::gtstore::GetNodeForKeyRequest& request, ::gtstore::GetNodeForKeyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetNodeForKey_, context, request, response);
}

void ManagerService::Stub::experimental_async::GetNodeForKey(::grpc::ClientContext* context, const ::gtstore::GetNodeForKeyRequest* request, ::gtstore::GetNodeForKeyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetNodeForKey_, context, request, response, std::move(f));
}

void ManagerService::Stub::experimental_async::GetNodeForKey(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::GetNodeForKeyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetNodeForKey_, context, request, response, std::move(f));
}

void ManagerService::Stub::experimental_async::GetNodeForKey(::grpc::ClientContext* context, const ::gtstore::GetNodeForKeyRequest* request, ::gtstore::GetNodeForKeyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetNodeForKey_, context, request, response, reactor);
}

void ManagerService::Stub::experimental_async::GetNodeForKey(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::GetNodeForKeyResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetNodeForKey_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtstore::GetNodeForKeyResponse>* ManagerService::Stub::AsyncGetNodeForKeyRaw(::grpc::ClientContext* context, const ::gtstore::GetNodeForKeyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::GetNodeForKeyResponse>::Create(channel_.get(), cq, rpcmethod_GetNodeForKey_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::gtstore::GetNodeForKeyResponse>* ManagerService::Stub::PrepareAsyncGetNodeForKeyRaw(::grpc::ClientContext* context, const ::gtstore::GetNodeForKeyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::GetNodeForKeyResponse>::Create(channel_.get(), cq, rpcmethod_GetNodeForKey_, context, request, false);
}

ManagerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ManagerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ManagerService::Service, ::gtstore::RegisterNodeRequest, ::gtstore::RegisterNodeResponse>(
          [](ManagerService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::gtstore::RegisterNodeRequest* req,
             ::gtstore::RegisterNodeResponse* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ManagerService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ManagerService::Service, ::gtstore::GetNodeForKeyRequest, ::gtstore::GetNodeForKeyResponse>(
          [](ManagerService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::gtstore::GetNodeForKeyRequest* req,
             ::gtstore::GetNodeForKeyResponse* resp) {
               return service->GetNodeForKey(ctx, req, resp);
             }, this)));
}

ManagerService::Service::~Service() {
}

::grpc::Status ManagerService::Service::Register(::grpc::ServerContext* context, const ::gtstore::RegisterNodeRequest* request, ::gtstore::RegisterNodeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ManagerService::Service::GetNodeForKey(::grpc::ServerContext* context, const ::gtstore::GetNodeForKeyRequest* request, ::gtstore::GetNodeForKeyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* StorageService_method_names[] = {
  "/gtstore.StorageService/Put",
  "/gtstore.StorageService/Get",
  "/gtstore.StorageService/Ping",
  "/gtstore.StorageService/TransferData",
};

std::unique_ptr< StorageService::Stub> StorageService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StorageService::Stub> stub(new StorageService::Stub(channel));
  return stub;
}

StorageService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Put_(StorageService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Get_(StorageService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ping_(StorageService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TransferData_(StorageService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StorageService::Stub::Put(::grpc::ClientContext* context, const ::gtstore::PutRequest& request, ::gtstore::PutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Put_, context, request, response);
}

void StorageService::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::gtstore::PutRequest* request, ::gtstore::PutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void StorageService::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::PutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, std::move(f));
}

void StorageService::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::gtstore::PutRequest* request, ::gtstore::PutResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

void StorageService::Stub::experimental_async::Put(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::PutResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Put_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtstore::PutResponse>* StorageService::Stub::AsyncPutRaw(::grpc::ClientContext* context, const ::gtstore::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::PutResponse>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::gtstore::PutResponse>* StorageService::Stub::PrepareAsyncPutRaw(::grpc::ClientContext* context, const ::gtstore::PutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::PutResponse>::Create(channel_.get(), cq, rpcmethod_Put_, context, request, false);
}

::grpc::Status StorageService::Stub::Get(::grpc::ClientContext* context, const ::gtstore::GetRequest& request, ::gtstore::GetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Get_, context, request, response);
}

void StorageService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::gtstore::GetRequest* request, ::gtstore::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void StorageService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::GetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void StorageService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::gtstore::GetRequest* request, ::gtstore::GetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

void StorageService::Stub::experimental_async::Get(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::GetResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtstore::GetResponse>* StorageService::Stub::AsyncGetRaw(::grpc::ClientContext* context, const ::gtstore::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::GetResponse>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::gtstore::GetResponse>* StorageService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext* context, const ::gtstore::GetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::GetResponse>::Create(channel_.get(), cq, rpcmethod_Get_, context, request, false);
}

::grpc::Status StorageService::Stub::Ping(::grpc::ClientContext* context, const ::gtstore::PingRequest& request, ::gtstore::PingResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void StorageService::Stub::experimental_async::Ping(::grpc::ClientContext* context, const ::gtstore::PingRequest* request, ::gtstore::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void StorageService::Stub::experimental_async::Ping(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::PingResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void StorageService::Stub::experimental_async::Ping(::grpc::ClientContext* context, const ::gtstore::PingRequest* request, ::gtstore::PingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

void StorageService::Stub::experimental_async::Ping(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::PingResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtstore::PingResponse>* StorageService::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::gtstore::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::PingResponse>::Create(channel_.get(), cq, rpcmethod_Ping_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::gtstore::PingResponse>* StorageService::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::gtstore::PingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::PingResponse>::Create(channel_.get(), cq, rpcmethod_Ping_, context, request, false);
}

::grpc::Status StorageService::Stub::TransferData(::grpc::ClientContext* context, const ::gtstore::TransferDataRequest& request, ::gtstore::TransferDataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TransferData_, context, request, response);
}

void StorageService::Stub::experimental_async::TransferData(::grpc::ClientContext* context, const ::gtstore::TransferDataRequest* request, ::gtstore::TransferDataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TransferData_, context, request, response, std::move(f));
}

void StorageService::Stub::experimental_async::TransferData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::TransferDataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TransferData_, context, request, response, std::move(f));
}

void StorageService::Stub::experimental_async::TransferData(::grpc::ClientContext* context, const ::gtstore::TransferDataRequest* request, ::gtstore::TransferDataResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TransferData_, context, request, response, reactor);
}

void StorageService::Stub::experimental_async::TransferData(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gtstore::TransferDataResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_TransferData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::gtstore::TransferDataResponse>* StorageService::Stub::AsyncTransferDataRaw(::grpc::ClientContext* context, const ::gtstore::TransferDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::TransferDataResponse>::Create(channel_.get(), cq, rpcmethod_TransferData_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::gtstore::TransferDataResponse>* StorageService::Stub::PrepareAsyncTransferDataRaw(::grpc::ClientContext* context, const ::gtstore::TransferDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::gtstore::TransferDataResponse>::Create(channel_.get(), cq, rpcmethod_TransferData_, context, request, false);
}

StorageService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::gtstore::PutRequest, ::gtstore::PutResponse>(
          [](StorageService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::gtstore::PutRequest* req,
             ::gtstore::PutResponse* resp) {
               return service->Put(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::gtstore::GetRequest, ::gtstore::GetResponse>(
          [](StorageService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::gtstore::GetRequest* req,
             ::gtstore::GetResponse* resp) {
               return service->Get(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::gtstore::PingRequest, ::gtstore::PingResponse>(
          [](StorageService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::gtstore::PingRequest* req,
             ::gtstore::PingResponse* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageService::Service, ::gtstore::TransferDataRequest, ::gtstore::TransferDataResponse>(
          [](StorageService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::gtstore::TransferDataRequest* req,
             ::gtstore::TransferDataResponse* resp) {
               return service->TransferData(ctx, req, resp);
             }, this)));
}

StorageService::Service::~Service() {
}

::grpc::Status StorageService::Service::Put(::grpc::ServerContext* context, const ::gtstore::PutRequest* request, ::gtstore::PutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::Get(::grpc::ServerContext* context, const ::gtstore::GetRequest* request, ::gtstore::GetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::Ping(::grpc::ServerContext* context, const ::gtstore::PingRequest* request, ::gtstore::PingResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageService::Service::TransferData(::grpc::ServerContext* context, const ::gtstore::TransferDataRequest* request, ::gtstore::TransferDataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace gtstore

